# Generated by Django 4.2 on 2023-04-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="naver_id_manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naver_id", models.CharField(max_length=20, verbose_name="아이디")),
                (
                    "naver_pw",
                    models.CharField(
                        default=None, max_length=20, null=True, verbose_name="비밀번호"
                    ),
                ),
                ("naver_name", models.CharField(max_length=20, verbose_name="이름")),
                (
                    "naver_gender",
                    models.CharField(
                        choices=[("M", "M"), ("F", "F"), ("U", "U")],
                        default="U",
                        max_length=6,
                        verbose_name="성별",
                    ),
                ),
                ("naver_birth", models.DateField(max_length=8, verbose_name="생년월일")),
                (
                    "naver_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "naver_country",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="국가"
                    ),
                ),
                (
                    "naver_join_ip",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="가입 ip"
                    ),
                ),
                (
                    "naver_real_status",
                    models.CharField(
                        choices=[("Y", "Y"), ("N", "N")],
                        default="N",
                        max_length=6,
                        verbose_name="실명여부",
                    ),
                ),
                (
                    "naver_login_status",
                    models.CharField(
                        choices=[("Y", "Y"), ("N", "N")],
                        default="N",
                        max_length=6,
                        verbose_name="로그인 가능여부",
                    ),
                ),
                (
                    "naver_last_login",
                    models.DateTimeField(auto_now=True, verbose_name="last login"),
                ),
            ],
        ),
    ]
