# Generated by Django 4.2 on 2023-04-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_alter_naver_id_manager_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="naver_id_manager",
            name="naver_gender",
            field=models.CharField(
                choices=[("남자", "male"), ("여자", "female "), ("상관없음", "other")],
                default="U",
                max_length=6,
                verbose_name="성별",
            ),
        ),
        migrations.AlterField(
            model_name="naver_id_manager",
            name="naver_login_status",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Y"), ("N", "N")],
                max_length=6,
                null=True,
                verbose_name="로그인 가능여부",
            ),
        ),
        migrations.AlterField(
            model_name="naver_id_manager",
            name="naver_real_status",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Y"), ("N", "N")],
                max_length=6,
                null=True,
                verbose_name="실명여부",
            ),
        ),
    ]
