# Generated by Django 4.2 on 2023-04-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0004_alter_naver_id_manager_naver_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="naver_id_manager",
            name="naver_mobile_agent",
            field=models.CharField(
                default=None, max_length=500, null=True, verbose_name="비밀번호"
            ),
        ),
        migrations.AddField(
            model_name="naver_id_manager",
            name="naver_pc_agent",
            field=models.CharField(
                default=None, max_length=500, null=True, verbose_name="PC 에이전트"
            ),
        ),
    ]
