# Generated by Django 4.2 on 2023-04-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0005_naver_id_manager_naver_mobile_agent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="naver_id_manager",
            options={"verbose_name": "네이버 계정 관리", "verbose_name_plural": "네이버 계정 관리"},
        ),
        migrations.AlterField(
            model_name="naver_id_manager",
            name="naver_mobile_agent",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="비밀번호"
            ),
        ),
        migrations.AlterField(
            model_name="naver_id_manager",
            name="naver_pc_agent",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="PC 에이전트"
            ),
        ),
    ]
