# Generated by Django 4.2.1 on 2023-05-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("N_Account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="naver_id_manager",
            name="naver_login_status",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="로그인 가능여부"
            ),
        ),
        migrations.AlterField(
            model_name="naver_id_manager",
            name="naver_real_status",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="실명여부"
            ),
        ),
    ]
