# Generated by Django 4.2 on 2023-04-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="user_pw",
            field=models.CharField(max_length=20, verbose_name="비밀번호"),
        ),
    ]
