# Generated by Django 4.2 on 2023-04-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0002_alter_account_user_pw"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="user_pw",),
    ]
