# Generated by Django 4.2 on 2023-04-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Naver", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="naver_person",
            name="Answer",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="답변"
            ),
        ),
        migrations.AlterField(
            model_name="naver_person",
            name="answer_ID",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="답변자 아아디"
            ),
        ),
        migrations.AlterField(
            model_name="naver_person",
            name="creat_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="작성일"
            ),
        ),
        migrations.AlterField(
            model_name="naver_person",
            name="question_ID",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="질문자 아이디"
            ),
        ),
    ]
