# Generated by Django 4.2.1 on 2023-05-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Naver", "0002_alter_naver_person_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="naver_person",
            name="adoption_status",
            field=models.BooleanField(
                choices=[("Y", "Y"), ("N", "N")], default="N", verbose_name="채택 여부"
            ),
        ),
        migrations.AlterField(
            model_name="naver_person",
            name="answer_status",
            field=models.BooleanField(
                choices=[("Y", "Y"), ("N", "N")], default="N", verbose_name="답변 작성 여부"
            ),
        ),
        migrations.AlterField(
            model_name="naver_person",
            name="question",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="질문"
            ),
        ),
        migrations.AlterField(
            model_name="naver_person",
            name="question_status",
            field=models.BooleanField(
                choices=[("Y", "Y"), ("N", "N")], default="N", verbose_name="질문 작성 여부"
            ),
        ),
    ]
