# Generated by Django 4.2 on 2023-04-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Naver", "0002_alter_naver_person_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="naver_person",
            name="naver_url",
            field=models.URLField(blank=True, null=True, verbose_name="지식인 URL"),
        ),
    ]
