# Generated by Django 4.2.1 on 2023-05-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Naver", "0003_alter_naver_person_adoption_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="naver_person",
            name="adoption_status",
            field=models.BooleanField(default=False, verbose_name="채택 여부"),
        ),
        migrations.AlterField(
            model_name="naver_person",
            name="answer_status",
            field=models.BooleanField(default=False, verbose_name="답변 작성 여부"),
        ),
        migrations.AlterField(
            model_name="naver_person",
            name="question_status",
            field=models.BooleanField(default=False, verbose_name="질문 작성 여부"),
        ),
    ]
